include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 80
  trailing_commas: automate

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_print: true
    avoid_redundant_argument_values: false
    unawaited_futures: true
    avoid_catches_without_on_clauses: false
    one_member_abstracts: false
